- hosts: prod
  user: ubuntu
  sudo: True
  roles:
    - ubuntu
    - deploy
    - prod-deploy
    - nginx-ssl
  vars:
      serverListenPort: "8090"
      serverListenAddress: "0.0.0.0"
      apiBackendDNSName: "api.shoutoutwith.us"
      adminContact: "aparrish@neosavvy.com"